### ISSUE TITLE
no result

### ISSUE THREAD

**Issue by GodoLucifer** [hustzxd/yolo2_to_caffe_tool#9]
参考您的prototxt,转化coco80类官网yolov2模型，能成果转化模型，并且读取region层参数（425*13*13，coco80类），但是运行detect.py，输出的box数目为0，并且没有话框，测试另外的dog.jpg图片也没结果，请问下我是不是哪些东西没弄好？

**Comment by hustzxd** [comment]
您好，好长时间没维护这个项目了，我猜想可能原因如下：
1. darknet 版本一直在更新，权重可能也更新过
2. 可以尝试一下 voc 版本的，如果可以的话，那就是这个版本可能没有添加对coco的支持

**Comment by GodoLucifer** [comment]
好的，谢谢您的建议啦，我这边尝试下 
------------------



于曙光
北京卓视智通


 联系我









 




------------------ 原始邮件 ------------------
发件人: "Joey"<notifications@github.com>; 
发送时间: 2019年7月11日(星期四) 晚上9:01
收件人: "hustzxd/z1"<z1@noreply.github.com>; 
抄送: "G.Y"<2283795350@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [hustzxd/z1] no result (#9)




您好，好长时间没维护这个项目了，我猜想可能原因如下：
  
darknet 版本一直在更新，权重可能也更新过
 
可以尝试一下 voc 版本的，如果可以的话，那就是这个版本可能没有添加对coco的支持
